language: python
python:
  - '2.7'
install:
  - python setup.py bdist
  - pip install .
script: run_tests
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=`python -c 'import cxmanage_api.__init__; print cxmanage_api.__init__.__version__'`
  - export GIT_TAG=$GIT_TAG.$TRAVIS_BUILD_NUMBER
  - echo $GIT_TAG
notifications:
  slack:
    secure: kJShCNMzboCvKYNAXU0hLjq487yYHoUBLdaNdhyFwt5qdA92ZhCJ+SePThVGFyy000y0ChjHSW9lwDce3vP/9O+WY7CD6qsjufLcm1UITe8osDegOtuc2xhNG9LUwv7EhZUtOoUS/zlCh5xNnIy1EbAY3fDWzlg2xQTijANf/IY8TNiwaHGH3x6wiC8ysDAT76oYto7u7DddR8wCDBvT0Ublhvh/01ZGRZcloHDpM6twMlOqveFChxZIibJinbEi72z1xMhyw59GBWUey31hD/etDNjBlzn23N/XuYvpW04zZoDoEdnf3Wx5LZf3c0G7AiKkynX6lZIYBK785VHNv3XeGx5/Jqxov1GZA1Gfo853P/hOLpMJcdpMNCMjyBm8jdAUPwwWYAZmpPaNMgkPljXXchvmd5BO9PDh3QCt5KeFXCMesD0/ZH/FkPLFaierbem8xN8pnjshdiVPOVhs4Znth+lvtBKUbJetztUSGL3NKm9mPIphs2Bn4x5YY2YL9XjgML9kT2zS3qWP8iEpwYXGfm1QH7Gj9Wx6YBD7Io/l675/Vg46zwSlJcNJGCcvBeD/BEKni1x23T659oVGTIFN3+pwXhvz9+FLPj+mwQ1lmpU147K3BHOLR69pJMJQ6tMFOXMy64JTXNkZ6ngn8fHYdVr+xHEzdOH6kw2t4lE=
