#!/usr/bin/env python

#Copyright 2012 Calxeda, Inc.  All Rights Reserved.

import unittest

from cxmanage_test import tftp_test, image_test, target_test, controller_test
test_modules = [tftp_test, image_test, controller_test]

def main():
    """ Load and run tests """
    loader = unittest.TestLoader()
    suite = unittest.TestSuite()
    for module in test_modules:
        suite.addTest(loader.loadTestsFromModule(module))
    unittest.TextTestRunner(verbosity=2).run(suite)

if __name__ == "__main__":
    main()
