#!/usr/bin/env python
"""Command line tool for managing a Calxeda cluster"""

import argparse
import os
import sys

from cx_manage_util.controller import Controller

def build_parser():
    """setup the argparse parser"""
    parser = argparse.ArgumentParser(
            description='Calxeda Server Management Utility')

    #global arguments
    parser.add_argument('-u', '--user', default='admin',
                        help='Username for login')
    parser.add_argument('-p', '--password', default='admin',
                        help='Password for login')
    parser.add_argument('-a', '--all', action='store_true',
                        help='Send command to all nodes reported by fabric \
                            (requires TFTP)')
    tftp_type = parser.add_mutually_exclusive_group(required=True)
    tftp_type.add_argument('-t', '--tftp',
            help='Connect to remote TFTP server at <ip:port>')
    tftp_type.add_argument('--localtftp',
            help='Host a local TFTP server listening on <ip:port>')

    subparsers = parser.add_subparsers()

    #power command
    power = subparsers.add_parser('power',
                                  help='control a9 power')
    power_subs = power.add_subparsers()

    power_on = power_subs.add_parser('on', help='boot the a9')
    power_on.set_defaults(power_mode='on')

    power_off = power_subs.add_parser('off', help='shut the a9 off')
    power_off.set_defaults(power_mode='off')

    power_reset = power_subs.add_parser('reset', help='reset the a9')
    power_reset.set_defaults(power_mode='reset')

    power.set_defaults(func=power_command)

    #fwupdate command
    fwupdate = subparsers.add_parser('fwupdate', help='update firmware')

    fwupdate.add_argument('image_type', metavar='IMAGE_TYPE',
                        help='type of image to update',
                        choices = list(sorted([
                            'DEL',
                            'DEL1',
                            'S2_ELF',
                            'SOC_ELF',
                            'A9_UEFI',
                            'A9_UBOOT',
                            'A9_EXEC',
                            'A9_ELF',
                            'SOCDATA',
                            'DTB',
                            'CDB',
                            'UBOOTENV',
                            'SEL',
                            'BOOT_LOG',
                            'UEFI_ENV',
                            'DIAG_ELF',
                        ]))
            )
    fwupdate.add_argument('filename', help='path to file to upload')
    fwupdate.add_argument('-s', '--simg', help='prepend SIMG to file',
                            default=False, action='store_true')
    fwupdate.set_defaults(func=fwupdate_command)
    
    parser.add_argument('hostname', help='hostname to target', nargs='+')

    return parser

def main():
    """Get args and go"""

    parser = build_parser()
    args = parser.parse_args()

    controller = Controller()

    if args.tftp:
        try:
            tftp_address, tftp_port = args.tftp.split(':')
            tftp_port = int(tftp_port)
        except ValueError:
            tftp_address = args.tftp
            tftp_port = 69
        controller.set_external_tftp_server(tftp_address, tftp_port)
    elif args.localtftp:
        try:
            tftp_address, tftp_port = args.localtftp.split(':')
            tftp_port = int(tftp_port)
        except ValueError:
            tftp_address = args.localtftp
            tftp_port = 69
        controller.set_internal_tftp_server(tftp_address, tftp_port)

    try:
        get_addresses(controller, args)
    except ValueError:
        print 'ERROR: Failed to get IP addresses'
        return 1

    sys.exit(args.func(controller, args))

def power_command(controller, args):
    """change the power state of a cluster or host"""
    controller.power_command('_group', args.power_mode)

    return 0

def fwupdate_command(controller, args):
    """update firmware on a cluster or host"""
    if not os.path.exists(args.filename):
        print 'ERROR: File %s does not exist' % args.filename
        return 1

    # Add image and execute command
    controller.add_image('_image', args.image_type, args.filename, args.simg)
    controller.update_firmware('_group', '_image')

    return 0

def get_addresses(controller, args):
    """get initial addresses"""
    addresses = set()
    for entry in args.hostname:
        try:
            # Treat the entry as an IP range
            start, end = entry.split('-')
            addresses.update(controller.get_targets_in_range(start, end))
        except ValueError:
            # Not an IP range, just add the address directly
            addresses.add(entry)

    if args.all:
        # Get targets from fabric
        fabric_addresses = set()
        for address in addresses:
            if not address in fabric_addresses:
                new_addresses = controller.get_targets_from_fabric(address,
                        args.user, args.password)
                fabric_addresses.update(new_addresses)
        addresses = addresses.union(fabric_addresses)

    # Add addresses to target group
    for address in addresses:
        controller.add_target('_group', address, args.user, args.password)

if __name__ == '__main__':
    main()
