#!/usr/bin/env python

#Copyright 2012 Calxeda, Inc.  All rights reserved.

"""Command line tool for creating a Calxeda firmware package"""

import argparse
import os
import sys

from cxmanage.controller import Controller

def build_parser():
    """setup the argparse parser"""
    parser = argparse.ArgumentParser(
            description='Calxeda firmware package creator')
    subparsers = parser.add_subparsers()

    #info command
    info = subparsers.add_parser('info', help='Display package info')
    info.set_defaults(func=info_command)

    #add command
    add = subparsers.add_parser('add',
            help='Create or add to a firmware package')
    add.add_argument('image_type', metavar='IMAGE_TYPE',
                        help='type of image to update',
                        type=lambda string: string.upper(),
                        choices = list(sorted([
                            'DEL',
                            'DEL1',
                            'S2_ELF',
                            'SOC_ELF',
                            'A9_UEFI',
                            'A9_UBOOT',
                            'A9_EXEC',
                            'A9_ELF',
                            'SOCDATA',
                            'DTB',
                            'CDB',
                            'UBOOTENV',
                            'SEL',
                            'BOOT_LOG',
                            'UEFI_ENV',
                            'DIAG_ELF',
                        ]))
            )
    simg_args = add.add_mutually_exclusive_group()
    simg_args.add_argument('--force-simg', help='Force addition of SIMG header',
                            default=False, action='store_true')
    simg_args.add_argument('--skip-simg', help='Skip addition of SIMG header',
                            default=False, action='store_true')
    add.add_argument('-v', '--version', help='Version for SIMG header',
                            default=None, type=int)
    add.add_argument('-d', '--daddr', help='Destination address for SIMG',
                            default=None, type=lambda x : int(x, 16))
    add.add_argument('--skip-crc32', help='Skip crc32 calculation for SIMG',
                            default=False, action='store_true')
    add.add_argument('filename', help='image path')
    add.set_defaults(func=add_command)

    parser.add_argument('package', help='target package')

    return parser

def validate_args(args):
    """ Bail out if the arguments don't make sense"""
    if args.func == add_command:
        if args.skip_simg and args.version:
            sys.exit('Invalid argument --version when supplied with --skip-simg')
        if args.skip_simg and args.daddr:
            sys.exit('Invalid argument --daddr when supplied with --skip-simg')
        if args.skip_simg and args.skip_crc32:
            sys.exit('Invalid argument --skip-crc32 when supplied with --skip-simg')

def main():
    """Get args and go"""
    parser = build_parser()
    args = parser.parse_args()
    validate_args(args)

    controller = Controller()

    sys.exit(args.func(controller, args))

def info_command(controller, args):
    """ Get package info """
    controller.add_image(args.package, 'PACKAGE')

    print
    controller.print_images()

    return 0

def add_command(controller, args):
    """ Create or add to a firmware package """
    if os.path.exists(args.package):
        controller.add_image(args.package, 'PACKAGE')

    simg = None
    if args.force_simg:
        simg = False
    elif args.skip_simg:
        simg = True

    controller.add_image(args.filename, args.image_type,
            simg, args.version, args.daddr, args.skip_crc32)
    controller.save_package(args.package)

    return 0

if __name__ == "__main__":
    main()
